Calculator
AtosReferenzApplikation/e2e-testing pull request #9
Opened 2019-07-10 08:40 UTC by Jonathan-Br

Taschenrechner für Unit Tests

2019-07-10 20:07 UTC, BenediktSt requested changes

2019-07-10 20:07 UTC, BenediktSt commented on src/app/jobr/Taschenrechner.java
> +    public static void main(String[] args)
Ich würde die Main Methode hier aus der Taschenrechnerklasse herauslassen.
In den Unit Tests hast du sicher schon gemerkt, dass das nicht notwendig ist und so ist die Klasse ein wenig sauberer

2019-07-11 16:49 UTC, thielet commented
BigDecimal wirft eine NullPointer Exception, wenn einer der Werte Null ist. Die calculate Methode sollte sicherstellen, dass zahl1 und zahl2 nicht null sind.

2019-07-11 19:38 UTC, BenediktSt approved these changes

2019-07-11 19:38 UTC, BenediktSt commented on src/app/jobr/Taschenrechner.java
> +     * Does a simple mathematical calculation using the BigDecimal number format to prevent floating point inaccuracy.
Die Kommentare kannst du noch raus hauen und dann wenn du willst noch Torstens Anmerkungen einarbeiten, dann kannst du es auch gleich mergen

2019-07-15 15:54 UTC, merged

2019-07-15 15:54 UTC, Jonathan-Br commented
Merged